apiVersion: v1
kind: ReplicationController
metadata:
  name: croc-hunter
spec:
  replicas: ${TPL_REPLICAS:-3}
  template:
    metadata:
      labels:
        app: croc-hunter
    spec:
      containers:
      - name: croc-hunter
        image: quay.io/flywire/croc-hunter:${TPL_ENVIRONMENT:-release}-${WERCKER_GIT_COMMIT}
        resources:
          requests:
            memory: "64M"
            cpu: "300m"
          limits:
            memory: "128M"
            cpu: "1"  
        ports:
        - containerPort: 8080
        securityContext:
          readOnlyRootFilesystem: true
      imagePullSecrets:
      - name: flywire-k8s-pull-secret
