apiVersion: v1
kind: ReplicationController
metadata:
  name: croc-hunter
spec:
  replicas: ${TPL_REPLICAS:-3}
  template:
    metadata:
      labels:
        name: croc-hunter
    spec:
      containers:
      - name: croc-hunter
        image: quay.io/flywire/croc-hunter:${TPL_ENVIRONMENT:-release}-${WERCKER_GIT_COMMIT}
        ports:
        - containerPort: 8080
