---
kind: Service
apiVersion: v1
metadata:
  name: croc-hunter
  labels:
    app: croc-hunter
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: croc-hunter
