---
kind: Service
apiVersion: v1
metadata:
  name: croc-hunter
  labels:
    app: croc-hunter
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: croc-hunter
  type: LoadBalancer
  volumeClaimTemplates:
  	- metadata:
        name: "mongodb"
      spec:
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: "1Gi"
