---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: croc-hunter
  labels:
    name: croc-hunter
spec:
  replicas: ${TPL_REPLICAS:-3}
  template:
    metadata:
      labels:
        name: croc-hunter
    spec:
      containers:
      - name: croc-hunter
        image: quay.io/flywire/croc-hunter:${TPL_ENVIRONMENT:-release}-${WERCKER_GIT_COMMIT}
        ports:
        - name: http-server
          containerPort: 8080
          protocol: TCP
      imagePullSecrets:
      - name: flywire-k8s-pull-secret
